### PR TITLE
Fix the rake task to not overwrite driver_options config

### PR DESCRIPTION
**Pull request by rylanc**

### CODE REVIEW

**Comment by nikhilmat** [comment]
does this really not work by default?

**Comment by rylanc** [comment]
Haha, nope. It was fixed in: https://github.com/modeset/teaspoon/commit/05544cb161686976dafda45be56d9284b46f6623

**Comment by nikhilmat** [comment]
@alfred accept!

**Comment by zp-alfred** [comment]
Accepted by nikhilmat!

**Pull request closed without merging**
